- name: Configured backend server
  hosts: mysql
  become: yes  
  tasks:
  - name: Disable current nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.buitin.command: dnf module enable nodejs:20 -y
    
  - name: Install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
    
