- name: Configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: Enable and start MySQL service
    ansible.builtin.service:
      name: musqld
      state: started
      enabled: yes
      